### ISSUE TITLE
typings file

### ISSUE THREAD

**Issue by adamjuhasz** [spencermountain/compromise#254]
The published package is missing the type file `nlp.d.ts`

``` bash
Adams-MacBook-Pro-5:nlp_compromise adamjuhasz$ ls -l
total 32
-rw-r--r--   1 adamjuhasz  staff  1080 Jan 27  2016 LICENSE.txt
-rw-r--r--   1 adamjuhasz  staff  4029 Jul  6 07:33 README.md
drwxr-xr-x   4 adamjuhasz  staff   136 Jul 27 08:42 builds
-rw-r--r--   1 adamjuhasz  staff  2626 Jun 20 17:38 changelog.md
-rw-r--r--   1 adamjuhasz  staff  2793 Jul 27 08:42 package.json
drwxr-xr-x  10 adamjuhasz  staff   340 Jul 27 08:42 src
```

**Comment by spencermountain** [comment]
yikes! thanks Adam! it's [right there](https://github.com/nlp-compromise/nlp_compromise/blob/master/nlp.d.ts), but maybe it's not being shipped with npm, because of the package.json settings.
Honestly, I've not figured out how to test this typefile format, and get lost whenever I research it.
What are you using it for?

**Comment by adamjuhasz** [comment]
I would have made a PR, but not sure how to fix this, it's in the repo and in package.json:typings so it must be some configuration setting for NPM... I thought someone here might know a quick answer, but I'll do a bit of googling.

I'm using nlp_compromise with our chatbot framework (https://github.com/fyndme/bot-framework) currently I just grabbed the d.ts file and threw it in manually.

**Comment by adamjuhasz** [comment]
@spencermountain, does it need to be added to the 'files' section of package.json?
#255 should do it

**Comment by spencermountain** [comment]
thanks man, do you have any feelings about jsdoc/flow annotions?
i'm working on a major api change and may add type annotations, and some auto-documentation, but haven't landed on which style to jump on yet.

**Comment by spencermountain** [comment]
the separate typings file like that is a bit of work, and not easy to like, validate the tests on or whatever.

**Comment by TheShashank** [comment]
wait so is there a typings file?
I did `typings search nlp` and `typings search compromise` but both returned with no results.
I'm loving the browser-based implementation.

**Comment by spencermountain** [comment]
thanks!
yeah, hah. well I'll admit I've looked and still haven't the slightest idea how to do this properly ;)
i have a tentative one [here](https://github.com/nlp-compromise/compromise/blob/master/compromise.d.ts) and we had a more thorough one for earlier versions.

i'm happy to support it going forward, the only requirement is that somehow we build a test for it - so that when it's incorrect I am told about it. Happy to support this any way.

-would really love some help doin this @TheShashank 
cheers

**Comment by WorldMaker** [comment]
@spencermountain The strongest test for types would be to use Typescript to build and check the library itself. ;)

I think there would be a good advantage to migrating the src to Typescript, and Typescript now has a range of migration options including starting with mostly just JSDoc annotations (and `// @ts-check` comments) if you wanted to try a more piecemeal approach than moving directly to ts files and Typescript type assertions.

**Comment by spencermountain** [comment]
Max! yes. i need someone like you.
yeah, is it worthwhile to run/build the unannotated source somehow as a test? 
ideally if we change the api, but forget to change the typing file, a test fails?
will merge anything. i haven't been able to keep-up with that typings-in-javascript stuff, but definitely understand the value of it.

**Comment by WorldMaker** [comment]
You can let Typescript build unannotated source to start to get an idea of type issues that its type system finds and a feel for the type information that it can inference from your existing code (a more "live" view of what you got from a one-off run of `dts-gen` for the current typing file). As you add type annotations you can watch it get better (and slowly get the type output better than the current type file giving up with an `any` as the return of the main function). Typescript supports starting with JSDoc-style type annotations as a first step if you are hesitant to jump straight to Typescript syntax/files.

At that point the type definitions would be a build artifact that directly updates as you update the API, and directly benefits as you JSDoc document the API.

Personally, I think there is a benefit to migrate more fully, more quickly to Typescript. I find it's much easier to use ES6/ES2015 (and more recent) syntax/tools in Typescript and that Typescript is simpler than Babel to get a good build pipeline to support both ES5 and ES6/ES2015+. Obviously there is some learning curve to that, but it could simplify your build process some, maybe.

**Comment by spencermountain** [comment]
hey max, you got a spare second to help me setup typescript typings for v12?

All the typings are working for the main library, but i've got a bunch of plugins that modify the prototype, and add new methods.
I've love to be able to add typings for the plugins, but haven't figured out a way.

so far, they look [like this](https://github.com/spencermountain/compromise/blob/linked-list/plugins/dates/src/index.js).

cheers

**Comment by WorldMaker** [comment]
Sure, I'd be happy to help.

Plugins like that are indeed a little tricky/complex. Typescript documentation refers to it as "[declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html)". Often the easiest pattern try to "merge" all the plugins into a shared interface and have the main library implement/extend the empty version of that interface for them to merge into.

I know from past experience that debugging declaration merges can be tricky (dealing with situations where Typescript wants to consider them separate interfaces instead of merging), and I'm happy to try to help, though I'm also probably a bit rusty on it. It can be useful to search DefinitelyTyped for the pattern to see how other libraries are doing it.

**Comment by spencermountain** [comment]
thank you!
