### ISSUE TITLE
Noun tags Actor and Activity are not returning any output

### ISSUE THREAD

**Issue by frunkyfrunk** [spencermountain/compromise#479]
I'm facing a problem with the tags for Actor and Activity. Both methods below are not returning any words.

nlp("I'm swimming").match('#Activity').out('normal')
nlp("I'm a plumber").match('#Actor').out('normal')

**Comment by spencermountain** [comment]
hey @frunkyfrunk yeah, if you want to see the tags for a document, you can do this:
```
nlp(`I'm swimming`).debug();
```
i think for that example, you'll want to use the `#Gerund` tag, instead of #Activity. If i can remember, the difference is a subtle one - `nlp('swimming is fun')` is a noun-use of the word, so I called it 'activity'. You can match both by doing this:
```
nlp(`I'm swimming, running is fun.`).match('(#Activity|Gerund)').out()
```

yeah, it looks like we stopped tagging [these examples](https://github.com/spencermountain/compromise/blob/c634f433f9d08ba40f606429e0f838a45097c76d/data/words/nouns/professions.js#L33) with the Actor tag. hmm, maybe we should.

either way, you can always throw some actor-words into a plugin/lexicon, like this:
```js
nlp(`i'm a plumber`,{plumber:'Actor',carpenter:'Actor'})
```
cheers
