### ISSUE TITLE
How to get all possible parts of speech for a word that may have multiple senses?

### ISSUE THREAD

**Issue by josephrocca** [spencermountain/compromise#508]
Is it possible with compromise to get a list of all possible tags for a word? I'm trying to build a little script that allows me to filter out all non-nouns, or all non-adjectives, etc. from a word list. Is this sort of thing possible with compromise?

[Here's a quick script](https://gist.github.com/josephrocca/332f8001850cbf880de9f2d8dfc6e4fb) I wrote to show that compromise currently doesn't properly detect many nouns, especially if they also have an adjective/adverb/etc. sense.

Thanks!

**Comment by spencermountain** [comment]
oh hey, that's helpful. Do you see any helpful patterns in the missing nouns?
I try not to list-out possible nouns, because there's too many in the world. But if there are patterns like suffixes, in that list, where those words are being mis-classified, that could be really helpful.

you can see all the tags [here](https://beta.observablehq.com/@spencermountain/compromise-tags)
