### ISSUE TITLE
Infinite looping with this chunk of text after version 11.9.0

### ISSUE THREAD

**Issue by Jun711** [spencermountain/compromise#575]
Thank you for the great nlp package, Spencer. I hope it stays awesome so I should report this issue that I found with the latest releases.

## Issue
When text from the attached text document pasted into nlp function, it seems to be running into an infinite loop with version 11.13 which I installed via npm. I pasted the same text onto the demo site. https://observablehq.com/@spencermountain/compromise-normalization and it froze the site too(check the screenshot).

## Test Case
[text-causing-compromise-nlp-infinite-loop.txt](https://github.com/spencermountain/compromise/files/2974573/text-causing-compromise-nlp-infinite-loop.txt)

## Behavior
![compromise-nlp-infinite-loop-with-this-text](https://user-images.githubusercontent.com/6880939/54482573-d8721380-4802-11e9-9463-c21434d8dc4a.png)

## Possible Cause
However, it was working with version 10.2.2 that I had before I updated my compromise package. Thus, I installed older versions of  compromise and found out that it is working with version 11.9.0. I guess something added after version 11.9.0 caused it to happen.

**Comment by spencermountain** [comment]
hey @Jun711 thanks so much for filing this bug.
I'm afraid it's a [known issue](https://github.com/spencermountain/compromise/issues/511) with a badly-written regex, triggered by a sequence of periods after a word, without a space in between - like your example illustrates perfectly.

I've started a full-rewrite of the punctuation/whitespace parser for v12, so it will be fixed in that release (promise!) 

in the meantime, i'd run any similar input through a regex, to strip these out.
```js
text=text.replace(/\.{5}/, ' ')
doc=nlp(text)
```
sorry about this!
cheers
