### ISSUE TITLE
Conditional tagging through plugins

### ISSUE THREAD

**Issue by GuySartorelli** [spencermountain/compromise#625]
Is there currently a way to have conditional tags through plugins? If not, I think that would be a really powerful feature to add.

For example, I am setting up tags to help me identify different types of queries (both that are and are _not_ phrased as questions).
So in this below conceptual example, I want to define 'placed' as a `#LocationQuery`, but only if the sentence in which it is found is a question, and does not start with the string/word/term 'how':
```javascript
plugin = {
  words: {
    'placed': {
      tag: 'LocationQuery',
      except: '!isQuestion, startsWith(how)'
    }
}
```

For backwards compatibility, if there are no conditions, this would still read `words: {'placed': 'LocationQuery'}`

**Comment by spencermountain** [comment]
hi @GuySartorelli it's an interesting idea. You can always implement this sort of thing using `match().tag()` sequences - that's how that sort of logic is handled in the tagger itself.

'except' logic can be handled like this:
```js
let doc = nlp('he placed the pin. How is it placed?')

let m=doc.if('placed').ifNo('^how') 
```
that sort of thing.

i steer you towards doing that, because the plugin scheme is changing in v12. Using a sequence of Match/if/ifNo/tag statements is how I recommend doing this sort of work right now.

cheers!
