### ISSUE TITLE
full-sentence whitespace in .json text

### ISSUE THREAD

**Issue by kwasimensah** [spencermountain/compromise#627]
nlp("I love apples. Yes I do.").match("apples").replaceWith("peaches").all().out("text") returns:

"I love peaches.Yes I do."

It would ideally output:

"I love peaches. Yes I do."

compomise version: 11.14.3

**Comment by spencermountain** [comment]
hi @kwasimensah - good eye.
This should be fixed in the next release, which is expected in a few weeks.
cheers

**Comment by Jun711** [comment]
@spencermountain 
This doesn't seem to happen in version 11.12.5.

```
let nlpObj = nlp('I love peaches. Yes I do.');
const sen = nlpObj.sentences().data();
```

**Comment by spencermountain** [comment]
hey, yup and this is fixed now in 12.2.0 - 
https://runkit.com/spencermountain/5dea71e9cf41210019671ac3
thanks for your patience

**Comment by Jun711** [comment]
@spencermountain I have a question. 
I think with version 11.12.5, it doesn't remove the space at the end of a sentence but with version 12, it trim spaces of a sentences? 

```
let nlpObj = nlp('I love peaches. Yes I do. ');
const sen = nlpObj.sentences().data();
```

**Comment by spencermountain** [comment]
thanks @Jun711

**Comment by Jun711** [comment]
@spencermountain Thanks for replying.
I think either way is fine. I just wanted to know if you will keep spaces at the end of input text. 
With version 11.12.5, it seems to keep but with version 12, it seems to remove. 

By reopening this issue, are you changing it to keep spaces at the end of input text?

**Comment by spencermountain** [comment]
hey @Jun711 sorry for the delay on this, looks like it was an intentional but undocumented change in v12.
You can add .data({trim:false}) to disable this:

```js
let doc = nlp('I love peaches. Yes I do. ')
console.log(doc.sentences().json({ trim: false }))
```
(.data() is an alias for .json())

The reason it trims by default now is to keep the data clean for things like `doc.nouns().json()` - users shouldn't need to work-out the pre/post whitespace in those kind of cases. `sentences().json()` is a good case where you may want pre/post whitespace, but I didn't want to add some magic condition for that.

in the docs now [here](https://observablehq.com/@spencermountain/compromise-json)
cheers
