### ISSUE TITLE
How the adjectives are tagged 

### ISSUE THREAD

**Issue by gagan-bansal** [spencermountain/compromise#820]
Why the word 'satish' is tagged as adjective?
```node
> nlp('satish').out('tags')[0].tags
[ 'Adjective' ]
```
While 'gagan' is not tagged as adjective.
```node
> nlp('gagan').out('tags')[0].tags
[ 'Noun', 'Singular' ]
```

There may not be a bug, but I am curious to know.

**Comment by spencermountain** [comment]
hey @gagan-bansal sorry I missed this a few days ago
you can see a trace for the tagger by setting `nlp.verbose(true)` before the call

satish is caught by the 'ish' suffix, like 'foolish'
gagan fallsback to a noun because it misses all patterns. We default to Nouns for unknown words.

I'd love to help improve the tagger for indian vocab, please let me know if you find more issues, or want to help improve things.
cheers

**Comment by gagan-bansal** [comment]
@spencermountain thank you for the explanation.  Verbose will help a lot.

Sure, I'll report any issue I find while using for Indian context or otherwise.
