### ISSUE TITLE
Are the minified builds still supposed to support ES5?

### ISSUE THREAD

**Issue by fapnip** [spencermountain/compromise#882]
13.10.6 seems to be the last build that supports ES5, but the text here strongly implies they should be ES5 when is says "this is the current-size of the minified library (in ES5)":
https://observablehq.com/@spencermountain/compromise-filesize

Is this a mistake, or has ES5 been dropped?

**Comment by spencermountain** [comment]
hey @fapnip sorry about this. v14 is formally dropping support for es5, in a few weeks.
I'm curious - what error are you seeing? 13.10.6 is babeled-down, and should work in var-only environments.
cheers

**Comment by fapnip** [comment]
13.10.6 is ES5, but if you look at anything newer, like...
https://unpkg.com/compromise@13.11.4/builds/compromise.min.js
...you'll see it's not.

**Comment by spencermountain** [comment]
hey @fapnip - as of v14 the builds are es6, and 'evergreen' meaning they must be babeled-down for es5.

I was a hold-out. I like shipping es5. Since Microsoft [dropped ie](https://www.theverge.com/2021/5/19/22443997/microsoft-internet-explorer-end-of-support-date) and node [dropped 12](https://nodejs.org/en/about/releases/), my understanding is that releasing es6 is best-practice for libraries, and end-users can babel for different environments. 
cheers
