### ISSUE TITLE
Word derivation

### ISSUE THREAD

**Issue by webjay** [spencermountain/compromise#987]
When a user is uploading a CSV file, I am trying to guess which field is the name, start date, employment type etc.

- For names I use `nlp('Jacob is a sailor').people()`.
- For dates I use [compromise-dates](https://github.com/spencermountain/compromise/tree/master/plugins/dates) with `nlp('I love September').dates().get().length > 0`.

Please let me know if there is a smarter way.

As for _employment type_ I do it this way:
```
nlp.plugin({
  words: {
    "fulltime": "EmploymentType",
    "parttime": "EmploymentType",
    "internship": "EmploymentType",
    "freelance": "EmploymentType",
    "contract": "EmploymentType",
    "volunteer": "EmploymentType"
  }
});

const isEmploymentType = (text) => nlp(text.toLowerCase()).has('#EmploymentType');
```

- `isEmploymentType('I do freelance work')` ✅
- `isEmploymentType('I am a freelancer')` 🚩

Is there a way I can make it see freelance, freelancer, freelancing, free-lance etc as #EmploymentType?

**Comment by spencermountain** [comment]
hey Jacob - yep that sounds like a reasonable approach.  You could also do `nlp('I love September').has('#Date')`

There's also no harm in stuffing a ton of custom derivations in the lexicon - that's what we do internally.
to support the dashed form, you could do this:
```js
nlp.world().model.one.prefixes['free'] = true
console.log(nlp('free-lance ').has('freelance'))
```
honestly though, i would probably just blast all the derivations out manually.

compromise will automatically derive any verbs you pass in. This may help:
```js
nlp('freelancing', { freelance: 'Infinitive' }).debug()
```
this is a little awkward for your project - because EmploymentType could be Noun or verb.

this, for example, won't tag EmploymentType:
```js
nlp('freelancing', { freelance: ['Infinitive', 'EmploymentType'] }).debug()
```

hmmm. yep - i'd just pass a big object in! That's how i'd do it.
cheers
